sonar.projectKey=woolies-edge-fleet-ztp
sonar.projectName=Woolies Edge Fleet ZTP
sonar.sources=.
sonar.inclusions=**/*.yml,**/*.yaml,**/*.hcl,**/*.sh
sonar.exclusions=**/output/**,**/.git/**

sonar.sourceEncoding=UTF-8