apiVersion: v1
kind: Service
metadata:
  name: dds-gateway
  namespace: woolies-iot
  labels:
    app: dds-gateway
    tier: edge-messaging
spec:
  selector:
    app: dds-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090